
spring:
    datasource:
        name: source
        url: jdbc:mysql://127.0.0.1:3306/forum?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    mvc:  
        view:  
            prefix: /  
            suffix: .jsp
# 配置日志输出的级别,输出格式%p%m%n 级别 内容 换行
logging:
    level:
        root: trace
        com.tmf.bss.dao: trace
mybatis: 
  mapperLocations: classpath*:mappers/*.xml
  typeAliasesPackage: com.tmf.bbs
server:
    port: 8080
